//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PensionPortal.NAVWS {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Pension_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/Pension")]
    public partial class Pension : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckPensionerLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckPensionerPasswordChangedOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckValidPensionerNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneratePensionStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberBeneficiariesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMonthlyPensionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPayScheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPayrollPeriodsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPensionerEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPensionerNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPensionerProfileDetails1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPensionerProfileDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUpdatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback LifeCertificate1OperationCompleted;
        
        private System.Threading.SendOrPostCallback LifeCertificateOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginForUnchangedPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback PensionerLiabilityStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePensionerAutoGenPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePensionerPasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Pension() {
            this.Url = global::PensionPortal.Properties.Settings.Default.PensionPortal_NAVWS_Pension;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckPensionerLoginCompletedEventHandler CheckPensionerLoginCompleted;
        
        /// <remarks/>
        public event CheckPensionerPasswordChangedCompletedEventHandler CheckPensionerPasswordChangedCompleted;
        
        /// <remarks/>
        public event CheckValidPensionerNoCompletedEventHandler CheckValidPensionerNoCompleted;
        
        /// <remarks/>
        public event GeneratePensionStatementCompletedEventHandler GeneratePensionStatementCompleted;
        
        /// <remarks/>
        public event GetMemberBeneficiariesCompletedEventHandler GetMemberBeneficiariesCompleted;
        
        /// <remarks/>
        public event GetMonthlyPensionCompletedEventHandler GetMonthlyPensionCompleted;
        
        /// <remarks/>
        public event GetPayScheduleCompletedEventHandler GetPayScheduleCompleted;
        
        /// <remarks/>
        public event GetPayrollPeriodsCompletedEventHandler GetPayrollPeriodsCompleted;
        
        /// <remarks/>
        public event GetPensionerEmailCompletedEventHandler GetPensionerEmailCompleted;
        
        /// <remarks/>
        public event GetPensionerNameCompletedEventHandler GetPensionerNameCompleted;
        
        /// <remarks/>
        public event GetPensionerProfileDetails1CompletedEventHandler GetPensionerProfileDetails1Completed;
        
        /// <remarks/>
        public event GetPensionerProfileDetailsCompletedEventHandler GetPensionerProfileDetailsCompleted;
        
        /// <remarks/>
        public event GetUpdatesCompletedEventHandler GetUpdatesCompleted;
        
        /// <remarks/>
        public event LifeCertificate1CompletedEventHandler LifeCertificate1Completed;
        
        /// <remarks/>
        public event LifeCertificateCompletedEventHandler LifeCertificateCompleted;
        
        /// <remarks/>
        public event LoginForUnchangedPasswordCompletedEventHandler LoginForUnchangedPasswordCompleted;
        
        /// <remarks/>
        public event PensionerLiabilityStatementCompletedEventHandler PensionerLiabilityStatementCompleted;
        
        /// <remarks/>
        public event UpdatePensionerAutoGenPasswordCompletedEventHandler UpdatePensionerAutoGenPasswordCompleted;
        
        /// <remarks/>
        public event UpdatePensionerPasswordCompletedEventHandler UpdatePensionerPasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:CheckPensionerLogin", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="CheckPensionerLogin_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CheckPensionerLogin(string username, string userpassword) {
            object[] results = this.Invoke("CheckPensionerLogin", new object[] {
                        username,
                        userpassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPensionerLoginAsync(string username, string userpassword) {
            this.CheckPensionerLoginAsync(username, userpassword, null);
        }
        
        /// <remarks/>
        public void CheckPensionerLoginAsync(string username, string userpassword, object userState) {
            if ((this.CheckPensionerLoginOperationCompleted == null)) {
                this.CheckPensionerLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPensionerLoginOperationCompleted);
            }
            this.InvokeAsync("CheckPensionerLogin", new object[] {
                        username,
                        userpassword}, this.CheckPensionerLoginOperationCompleted, userState);
        }
        
        private void OnCheckPensionerLoginOperationCompleted(object arg) {
            if ((this.CheckPensionerLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPensionerLoginCompleted(this, new CheckPensionerLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:CheckPensionerPasswordChanged", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="CheckPensionerPasswordChanged_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CheckPensionerPasswordChanged(string username) {
            object[] results = this.Invoke("CheckPensionerPasswordChanged", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPensionerPasswordChangedAsync(string username) {
            this.CheckPensionerPasswordChangedAsync(username, null);
        }
        
        /// <remarks/>
        public void CheckPensionerPasswordChangedAsync(string username, object userState) {
            if ((this.CheckPensionerPasswordChangedOperationCompleted == null)) {
                this.CheckPensionerPasswordChangedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPensionerPasswordChangedOperationCompleted);
            }
            this.InvokeAsync("CheckPensionerPasswordChanged", new object[] {
                        username}, this.CheckPensionerPasswordChangedOperationCompleted, userState);
        }
        
        private void OnCheckPensionerPasswordChangedOperationCompleted(object arg) {
            if ((this.CheckPensionerPasswordChangedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPensionerPasswordChangedCompleted(this, new CheckPensionerPasswordChangedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:CheckValidPensionerNo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="CheckValidPensionerNo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CheckValidPensionerNo(string username) {
            object[] results = this.Invoke("CheckValidPensionerNo", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckValidPensionerNoAsync(string username) {
            this.CheckValidPensionerNoAsync(username, null);
        }
        
        /// <remarks/>
        public void CheckValidPensionerNoAsync(string username, object userState) {
            if ((this.CheckValidPensionerNoOperationCompleted == null)) {
                this.CheckValidPensionerNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckValidPensionerNoOperationCompleted);
            }
            this.InvokeAsync("CheckValidPensionerNo", new object[] {
                        username}, this.CheckValidPensionerNoOperationCompleted, userState);
        }
        
        private void OnCheckValidPensionerNoOperationCompleted(object arg) {
            if ((this.CheckValidPensionerNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckValidPensionerNoCompleted(this, new CheckValidPensionerNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:GeneratePensionStatement", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="GeneratePensionStatement_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GeneratePensionStatement(string username, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime startDate, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime endDate, string fileNameFromApp) {
            this.Invoke("GeneratePensionStatement", new object[] {
                        username,
                        startDate,
                        endDate,
                        fileNameFromApp});
        }
        
        /// <remarks/>
        public void GeneratePensionStatementAsync(string username, System.DateTime startDate, System.DateTime endDate, string fileNameFromApp) {
            this.GeneratePensionStatementAsync(username, startDate, endDate, fileNameFromApp, null);
        }
        
        /// <remarks/>
        public void GeneratePensionStatementAsync(string username, System.DateTime startDate, System.DateTime endDate, string fileNameFromApp, object userState) {
            if ((this.GeneratePensionStatementOperationCompleted == null)) {
                this.GeneratePensionStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneratePensionStatementOperationCompleted);
            }
            this.InvokeAsync("GeneratePensionStatement", new object[] {
                        username,
                        startDate,
                        endDate,
                        fileNameFromApp}, this.GeneratePensionStatementOperationCompleted, userState);
        }
        
        private void OnGeneratePensionStatementOperationCompleted(object arg) {
            if ((this.GeneratePensionStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneratePensionStatementCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:GetMemberBeneficiaries", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="GetMemberBeneficiaries_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetMemberBeneficiaries(string username) {
            object[] results = this.Invoke("GetMemberBeneficiaries", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberBeneficiariesAsync(string username) {
            this.GetMemberBeneficiariesAsync(username, null);
        }
        
        /// <remarks/>
        public void GetMemberBeneficiariesAsync(string username, object userState) {
            if ((this.GetMemberBeneficiariesOperationCompleted == null)) {
                this.GetMemberBeneficiariesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberBeneficiariesOperationCompleted);
            }
            this.InvokeAsync("GetMemberBeneficiaries", new object[] {
                        username}, this.GetMemberBeneficiariesOperationCompleted, userState);
        }
        
        private void OnGetMemberBeneficiariesOperationCompleted(object arg) {
            if ((this.GetMemberBeneficiariesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberBeneficiariesCompleted(this, new GetMemberBeneficiariesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:GetMonthlyPension", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="GetMonthlyPension_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetMonthlyPension(string pensiorNo) {
            object[] results = this.Invoke("GetMonthlyPension", new object[] {
                        pensiorNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMonthlyPensionAsync(string pensiorNo) {
            this.GetMonthlyPensionAsync(pensiorNo, null);
        }
        
        /// <remarks/>
        public void GetMonthlyPensionAsync(string pensiorNo, object userState) {
            if ((this.GetMonthlyPensionOperationCompleted == null)) {
                this.GetMonthlyPensionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMonthlyPensionOperationCompleted);
            }
            this.InvokeAsync("GetMonthlyPension", new object[] {
                        pensiorNo}, this.GetMonthlyPensionOperationCompleted, userState);
        }
        
        private void OnGetMonthlyPensionOperationCompleted(object arg) {
            if ((this.GetMonthlyPensionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMonthlyPensionCompleted(this, new GetMonthlyPensionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:GetPaySchedule", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="GetPaySchedule_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetPaySchedule() {
            object[] results = this.Invoke("GetPaySchedule", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPayScheduleAsync() {
            this.GetPayScheduleAsync(null);
        }
        
        /// <remarks/>
        public void GetPayScheduleAsync(object userState) {
            if ((this.GetPayScheduleOperationCompleted == null)) {
                this.GetPayScheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPayScheduleOperationCompleted);
            }
            this.InvokeAsync("GetPaySchedule", new object[0], this.GetPayScheduleOperationCompleted, userState);
        }
        
        private void OnGetPayScheduleOperationCompleted(object arg) {
            if ((this.GetPayScheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPayScheduleCompleted(this, new GetPayScheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:GetPayrollPeriods", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="GetPayrollPeriods_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetPayrollPeriods() {
            object[] results = this.Invoke("GetPayrollPeriods", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPayrollPeriodsAsync() {
            this.GetPayrollPeriodsAsync(null);
        }
        
        /// <remarks/>
        public void GetPayrollPeriodsAsync(object userState) {
            if ((this.GetPayrollPeriodsOperationCompleted == null)) {
                this.GetPayrollPeriodsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPayrollPeriodsOperationCompleted);
            }
            this.InvokeAsync("GetPayrollPeriods", new object[0], this.GetPayrollPeriodsOperationCompleted, userState);
        }
        
        private void OnGetPayrollPeriodsOperationCompleted(object arg) {
            if ((this.GetPayrollPeriodsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPayrollPeriodsCompleted(this, new GetPayrollPeriodsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:GetPensionerEmail", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="GetPensionerEmail_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetPensionerEmail(string username) {
            object[] results = this.Invoke("GetPensionerEmail", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPensionerEmailAsync(string username) {
            this.GetPensionerEmailAsync(username, null);
        }
        
        /// <remarks/>
        public void GetPensionerEmailAsync(string username, object userState) {
            if ((this.GetPensionerEmailOperationCompleted == null)) {
                this.GetPensionerEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPensionerEmailOperationCompleted);
            }
            this.InvokeAsync("GetPensionerEmail", new object[] {
                        username}, this.GetPensionerEmailOperationCompleted, userState);
        }
        
        private void OnGetPensionerEmailOperationCompleted(object arg) {
            if ((this.GetPensionerEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPensionerEmailCompleted(this, new GetPensionerEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:GetPensionerName", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="GetPensionerName_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetPensionerName(string username) {
            object[] results = this.Invoke("GetPensionerName", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPensionerNameAsync(string username) {
            this.GetPensionerNameAsync(username, null);
        }
        
        /// <remarks/>
        public void GetPensionerNameAsync(string username, object userState) {
            if ((this.GetPensionerNameOperationCompleted == null)) {
                this.GetPensionerNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPensionerNameOperationCompleted);
            }
            this.InvokeAsync("GetPensionerName", new object[] {
                        username}, this.GetPensionerNameOperationCompleted, userState);
        }
        
        private void OnGetPensionerNameOperationCompleted(object arg) {
            if ((this.GetPensionerNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPensionerNameCompleted(this, new GetPensionerNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:GetPensionerProfileDetails1", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="GetPensionerProfileDetails1_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetPensionerProfileDetails1(string username) {
            object[] results = this.Invoke("GetPensionerProfileDetails1", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPensionerProfileDetails1Async(string username) {
            this.GetPensionerProfileDetails1Async(username, null);
        }
        
        /// <remarks/>
        public void GetPensionerProfileDetails1Async(string username, object userState) {
            if ((this.GetPensionerProfileDetails1OperationCompleted == null)) {
                this.GetPensionerProfileDetails1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPensionerProfileDetails1OperationCompleted);
            }
            this.InvokeAsync("GetPensionerProfileDetails1", new object[] {
                        username}, this.GetPensionerProfileDetails1OperationCompleted, userState);
        }
        
        private void OnGetPensionerProfileDetails1OperationCompleted(object arg) {
            if ((this.GetPensionerProfileDetails1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPensionerProfileDetails1Completed(this, new GetPensionerProfileDetails1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:GetPensionerProfileDetails", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="GetPensionerProfileDetails_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetPensionerProfileDetails(string username) {
            object[] results = this.Invoke("GetPensionerProfileDetails", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPensionerProfileDetailsAsync(string username) {
            this.GetPensionerProfileDetailsAsync(username, null);
        }
        
        /// <remarks/>
        public void GetPensionerProfileDetailsAsync(string username, object userState) {
            if ((this.GetPensionerProfileDetailsOperationCompleted == null)) {
                this.GetPensionerProfileDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPensionerProfileDetailsOperationCompleted);
            }
            this.InvokeAsync("GetPensionerProfileDetails", new object[] {
                        username}, this.GetPensionerProfileDetailsOperationCompleted, userState);
        }
        
        private void OnGetPensionerProfileDetailsOperationCompleted(object arg) {
            if ((this.GetPensionerProfileDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPensionerProfileDetailsCompleted(this, new GetPensionerProfileDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:GetUpdates", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="GetUpdates_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetUpdates() {
            object[] results = this.Invoke("GetUpdates", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUpdatesAsync() {
            this.GetUpdatesAsync(null);
        }
        
        /// <remarks/>
        public void GetUpdatesAsync(object userState) {
            if ((this.GetUpdatesOperationCompleted == null)) {
                this.GetUpdatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUpdatesOperationCompleted);
            }
            this.InvokeAsync("GetUpdates", new object[0], this.GetUpdatesOperationCompleted, userState);
        }
        
        private void OnGetUpdatesOperationCompleted(object arg) {
            if ((this.GetUpdatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUpdatesCompleted(this, new GetUpdatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:LifeCertificate1", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="LifeCertificate1_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LifeCertificate1(string path, string fileName, string pensionerNo, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime period) {
            this.Invoke("LifeCertificate1", new object[] {
                        path,
                        fileName,
                        pensionerNo,
                        period});
        }
        
        /// <remarks/>
        public void LifeCertificate1Async(string path, string fileName, string pensionerNo, System.DateTime period) {
            this.LifeCertificate1Async(path, fileName, pensionerNo, period, null);
        }
        
        /// <remarks/>
        public void LifeCertificate1Async(string path, string fileName, string pensionerNo, System.DateTime period, object userState) {
            if ((this.LifeCertificate1OperationCompleted == null)) {
                this.LifeCertificate1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnLifeCertificate1OperationCompleted);
            }
            this.InvokeAsync("LifeCertificate1", new object[] {
                        path,
                        fileName,
                        pensionerNo,
                        period}, this.LifeCertificate1OperationCompleted, userState);
        }
        
        private void OnLifeCertificate1OperationCompleted(object arg) {
            if ((this.LifeCertificate1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LifeCertificate1Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:LifeCertificate", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="LifeCertificate_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LifeCertificate(string path, string fileName, string pensionerNo, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime period) {
            this.Invoke("LifeCertificate", new object[] {
                        path,
                        fileName,
                        pensionerNo,
                        period});
        }
        
        /// <remarks/>
        public void LifeCertificateAsync(string path, string fileName, string pensionerNo, System.DateTime period) {
            this.LifeCertificateAsync(path, fileName, pensionerNo, period, null);
        }
        
        /// <remarks/>
        public void LifeCertificateAsync(string path, string fileName, string pensionerNo, System.DateTime period, object userState) {
            if ((this.LifeCertificateOperationCompleted == null)) {
                this.LifeCertificateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLifeCertificateOperationCompleted);
            }
            this.InvokeAsync("LifeCertificate", new object[] {
                        path,
                        fileName,
                        pensionerNo,
                        period}, this.LifeCertificateOperationCompleted, userState);
        }
        
        private void OnLifeCertificateOperationCompleted(object arg) {
            if ((this.LifeCertificateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LifeCertificateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:LoginForUnchangedPassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="LoginForUnchangedPassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string LoginForUnchangedPassword(string username, string password) {
            object[] results = this.Invoke("LoginForUnchangedPassword", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginForUnchangedPasswordAsync(string username, string password) {
            this.LoginForUnchangedPasswordAsync(username, password, null);
        }
        
        /// <remarks/>
        public void LoginForUnchangedPasswordAsync(string username, string password, object userState) {
            if ((this.LoginForUnchangedPasswordOperationCompleted == null)) {
                this.LoginForUnchangedPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginForUnchangedPasswordOperationCompleted);
            }
            this.InvokeAsync("LoginForUnchangedPassword", new object[] {
                        username,
                        password}, this.LoginForUnchangedPasswordOperationCompleted, userState);
        }
        
        private void OnLoginForUnchangedPasswordOperationCompleted(object arg) {
            if ((this.LoginForUnchangedPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginForUnchangedPasswordCompleted(this, new LoginForUnchangedPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:PensionerLiabilityStatement", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="PensionerLiabilityStatement_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PensionerLiabilityStatement(string path, string fileName, string pensionerNo, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime startDate, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime endDate) {
            this.Invoke("PensionerLiabilityStatement", new object[] {
                        path,
                        fileName,
                        pensionerNo,
                        startDate,
                        endDate});
        }
        
        /// <remarks/>
        public void PensionerLiabilityStatementAsync(string path, string fileName, string pensionerNo, System.DateTime startDate, System.DateTime endDate) {
            this.PensionerLiabilityStatementAsync(path, fileName, pensionerNo, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void PensionerLiabilityStatementAsync(string path, string fileName, string pensionerNo, System.DateTime startDate, System.DateTime endDate, object userState) {
            if ((this.PensionerLiabilityStatementOperationCompleted == null)) {
                this.PensionerLiabilityStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPensionerLiabilityStatementOperationCompleted);
            }
            this.InvokeAsync("PensionerLiabilityStatement", new object[] {
                        path,
                        fileName,
                        pensionerNo,
                        startDate,
                        endDate}, this.PensionerLiabilityStatementOperationCompleted, userState);
        }
        
        private void OnPensionerLiabilityStatementOperationCompleted(object arg) {
            if ((this.PensionerLiabilityStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PensionerLiabilityStatementCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:UpdatePensionerAutoGenPassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="UpdatePensionerAutoGenPassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string UpdatePensionerAutoGenPassword(string username, string genpass) {
            object[] results = this.Invoke("UpdatePensionerAutoGenPassword", new object[] {
                        username,
                        genpass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePensionerAutoGenPasswordAsync(string username, string genpass) {
            this.UpdatePensionerAutoGenPasswordAsync(username, genpass, null);
        }
        
        /// <remarks/>
        public void UpdatePensionerAutoGenPasswordAsync(string username, string genpass, object userState) {
            if ((this.UpdatePensionerAutoGenPasswordOperationCompleted == null)) {
                this.UpdatePensionerAutoGenPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePensionerAutoGenPasswordOperationCompleted);
            }
            this.InvokeAsync("UpdatePensionerAutoGenPassword", new object[] {
                        username,
                        genpass}, this.UpdatePensionerAutoGenPasswordOperationCompleted, userState);
        }
        
        private void OnUpdatePensionerAutoGenPasswordOperationCompleted(object arg) {
            if ((this.UpdatePensionerAutoGenPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePensionerAutoGenPasswordCompleted(this, new UpdatePensionerAutoGenPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Pension:UpdatePensionerPassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", ResponseElementName="UpdatePensionerPassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Pension", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string UpdatePensionerPassword(string username, string password) {
            object[] results = this.Invoke("UpdatePensionerPassword", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePensionerPasswordAsync(string username, string password) {
            this.UpdatePensionerPasswordAsync(username, password, null);
        }
        
        /// <remarks/>
        public void UpdatePensionerPasswordAsync(string username, string password, object userState) {
            if ((this.UpdatePensionerPasswordOperationCompleted == null)) {
                this.UpdatePensionerPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePensionerPasswordOperationCompleted);
            }
            this.InvokeAsync("UpdatePensionerPassword", new object[] {
                        username,
                        password}, this.UpdatePensionerPasswordOperationCompleted, userState);
        }
        
        private void OnUpdatePensionerPasswordOperationCompleted(object arg) {
            if ((this.UpdatePensionerPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePensionerPasswordCompleted(this, new UpdatePensionerPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CheckPensionerLoginCompletedEventHandler(object sender, CheckPensionerLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPensionerLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPensionerLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CheckPensionerPasswordChangedCompletedEventHandler(object sender, CheckPensionerPasswordChangedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPensionerPasswordChangedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPensionerPasswordChangedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CheckValidPensionerNoCompletedEventHandler(object sender, CheckValidPensionerNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckValidPensionerNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckValidPensionerNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GeneratePensionStatementCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetMemberBeneficiariesCompletedEventHandler(object sender, GetMemberBeneficiariesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberBeneficiariesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberBeneficiariesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetMonthlyPensionCompletedEventHandler(object sender, GetMonthlyPensionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMonthlyPensionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMonthlyPensionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetPayScheduleCompletedEventHandler(object sender, GetPayScheduleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPayScheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPayScheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetPayrollPeriodsCompletedEventHandler(object sender, GetPayrollPeriodsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPayrollPeriodsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPayrollPeriodsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetPensionerEmailCompletedEventHandler(object sender, GetPensionerEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPensionerEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPensionerEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetPensionerNameCompletedEventHandler(object sender, GetPensionerNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPensionerNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPensionerNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetPensionerProfileDetails1CompletedEventHandler(object sender, GetPensionerProfileDetails1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPensionerProfileDetails1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPensionerProfileDetails1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetPensionerProfileDetailsCompletedEventHandler(object sender, GetPensionerProfileDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPensionerProfileDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPensionerProfileDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetUpdatesCompletedEventHandler(object sender, GetUpdatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUpdatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUpdatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void LifeCertificate1CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void LifeCertificateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void LoginForUnchangedPasswordCompletedEventHandler(object sender, LoginForUnchangedPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginForUnchangedPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginForUnchangedPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PensionerLiabilityStatementCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UpdatePensionerAutoGenPasswordCompletedEventHandler(object sender, UpdatePensionerAutoGenPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePensionerAutoGenPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePensionerAutoGenPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UpdatePensionerPasswordCompletedEventHandler(object sender, UpdatePensionerPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePensionerPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePensionerPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591