// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using b2b.BalanceEnquiry.Request;
//
//    var balanceEnquiryRequest = BalanceEnquiryRequest.FromJson(jsonString);

namespace b2b.PaymentAdvise.REQUEST
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);

    public class PaymentAdviseRequest
    {
        public Header header { get; set; }
        public Request Request { get; set; }
    }

    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
    public class Header
    {
        public string ServiceName { get; set; }
        public string messageid { get; set; }
        public string ConnectionID { get; set; }
        public string ConnectionPassword { get; set; }
    }

    public class Request
    {
        public string transactionReference { get; set; }
        public string requestId { get; set; }
        public string channelCode { get; set; }
        public string timestamp { get; set; }
        public string transactionAmount { get; set; }
        public string currency { get; set; }
        public string customerReference { get; set; }
        public string customerName { get; set; }
        public string customerMobileNumber { get; set; }
        public string balance { get; set; }
        public string narration { get; set; }
        public string creditAccountIdentifier { get; set; }
        public string organizationShortCode { get; set; }
        public string tillNumber { get; set; }
        public string payment_channel { get; set; }
        public string client_invoice_ref { get; set; }
        public string amount_paid { get; set; }
        public string invoice_amount { get; set; }
        public string status { get; set; }
        public string invoice_number { get; set; }
        public string payment_date { get; set; }
        public string token_hash { get; set; }
        public string last_payment_amount { get; set; }
        public List<PaymentReference> payment_reference { get; set; }
    }
    public class Disbursement
    {
        public string ftReference { get; set; }
        public string transactionDate { get;set; }
        public string amount {  get; set; }
        public string transactionStatus { get; set; }
        public string transactionMessage { get; set; }
        public string beneficiaryAccountNumber { get; set; }
        public string debitAccountNumber { get; set; }
        public string beneficiaryName { get; set; }
        public string transactionReference { get; set; }
        public string merchantId { get; set; }
    }
    public class PaymentReference
    {
        public string payment_reference { get; set; }
        public string payment_date { get; set; }
        public string inserted_at { get; set; }
        public string currency { get; set; }
        public string amount { get; set; }
    }


}





