// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using b2b.BalanceEnquiry.Response;
//
//    var balanceEnquiryResponse = BalanceEnquiryResponse.FromJson(jsonString);

namespace b2b.Accounts
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);


    public partial class Account
    {
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string Balance { get; set; }
        public string BillType { get; set; }
    }

}
