// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using b2b.BalanceEnquiry.Request;
//
//    var balanceEnquiryRequest = BalanceEnquiryRequest.FromJson(jsonString);

namespace b2b.AccountValidation.REQUEST
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
    public class Header
    {
        public string ServiceName { get; set; }
        public string messageid { get; set; }
        public string ConnectionID { get; set; }
        public string ConnectionPassword { get; set; }
    }

    public class Request
    {
        public string requestId { get; set; }
        public string customerReference { get; set; }
        public string organizationReference { get; set; }
    }

    public class AccountValidationRequest
    {
        public Header header { get; set; }
        public Request Request { get; set; }
    }



}
