// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using b2b.BalanceEnquiry.Response;
//
//    var balanceEnquiryResponse = BalanceEnquiryResponse.FromJson(jsonString);

namespace b2b.PaymentAdvise.RESPONSE
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
    public class PaymentAdviseResponse
    {
        public Header header { get; set; }
        public Response response { get; set; }
    }
      

    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
    public class Header
    {
        public string messageid { get; set; }
        public string statusCode { get; set; }
        public string statusDescription { get; set; }
    }

    public class Response
    {
        public string transactionID { get; set; }
        public string statusCode { get; set; }
        public string statusMessage { get; set; }
    }
    public class PesaFlowResponse
    {
        public string query_status { get; set; }
    }




}
