//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TrusteePortal.NAVWS {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Trustee_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/Trustee")]
    public partial class Trustee : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckTrusteeLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckTrusteePasswordChangedOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckValidTrusteeNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateP9OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveMemberCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllMembersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAssignedBoardsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBoardMeetingsAttended1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBoardMeetingsAttendedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberCountsByStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPensionerCountsByStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTrusteeDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTrusteeEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginForUnchangedPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTrusteeAutoGenPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTrusteePasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Trustee() {
            this.Url = global::TrusteePortal.Properties.Settings.Default.TrusteePortal_NAVWS_Trustee;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckTrusteeLoginCompletedEventHandler CheckTrusteeLoginCompleted;
        
        /// <remarks/>
        public event CheckTrusteePasswordChangedCompletedEventHandler CheckTrusteePasswordChangedCompleted;
        
        /// <remarks/>
        public event CheckValidTrusteeNoCompletedEventHandler CheckValidTrusteeNoCompleted;
        
        /// <remarks/>
        public event GenerateP9CompletedEventHandler GenerateP9Completed;
        
        /// <remarks/>
        public event GetActiveMemberCountCompletedEventHandler GetActiveMemberCountCompleted;
        
        /// <remarks/>
        public event GetAllMembersCompletedEventHandler GetAllMembersCompleted;
        
        /// <remarks/>
        public event GetAssignedBoardsCompletedEventHandler GetAssignedBoardsCompleted;
        
        /// <remarks/>
        public event GetBoardMeetingsAttended1CompletedEventHandler GetBoardMeetingsAttended1Completed;
        
        /// <remarks/>
        public event GetBoardMeetingsAttendedCompletedEventHandler GetBoardMeetingsAttendedCompleted;
        
        /// <remarks/>
        public event GetMemberCountsByStatusCompletedEventHandler GetMemberCountsByStatusCompleted;
        
        /// <remarks/>
        public event GetPensionerCountsByStatusCompletedEventHandler GetPensionerCountsByStatusCompleted;
        
        /// <remarks/>
        public event GetTrusteeDetailsCompletedEventHandler GetTrusteeDetailsCompleted;
        
        /// <remarks/>
        public event GetTrusteeEmailCompletedEventHandler GetTrusteeEmailCompleted;
        
        /// <remarks/>
        public event LoginForUnchangedPasswordCompletedEventHandler LoginForUnchangedPasswordCompleted;
        
        /// <remarks/>
        public event UpdateTrusteeAutoGenPasswordCompletedEventHandler UpdateTrusteeAutoGenPasswordCompleted;
        
        /// <remarks/>
        public event UpdateTrusteePasswordCompletedEventHandler UpdateTrusteePasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:CheckTrusteeLogin", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="CheckTrusteeLogin_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CheckTrusteeLogin(string username, string userpassword) {
            object[] results = this.Invoke("CheckTrusteeLogin", new object[] {
                        username,
                        userpassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckTrusteeLoginAsync(string username, string userpassword) {
            this.CheckTrusteeLoginAsync(username, userpassword, null);
        }
        
        /// <remarks/>
        public void CheckTrusteeLoginAsync(string username, string userpassword, object userState) {
            if ((this.CheckTrusteeLoginOperationCompleted == null)) {
                this.CheckTrusteeLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckTrusteeLoginOperationCompleted);
            }
            this.InvokeAsync("CheckTrusteeLogin", new object[] {
                        username,
                        userpassword}, this.CheckTrusteeLoginOperationCompleted, userState);
        }
        
        private void OnCheckTrusteeLoginOperationCompleted(object arg) {
            if ((this.CheckTrusteeLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckTrusteeLoginCompleted(this, new CheckTrusteeLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:CheckTrusteePasswordChanged", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="CheckTrusteePasswordChanged_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CheckTrusteePasswordChanged(string username) {
            object[] results = this.Invoke("CheckTrusteePasswordChanged", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckTrusteePasswordChangedAsync(string username) {
            this.CheckTrusteePasswordChangedAsync(username, null);
        }
        
        /// <remarks/>
        public void CheckTrusteePasswordChangedAsync(string username, object userState) {
            if ((this.CheckTrusteePasswordChangedOperationCompleted == null)) {
                this.CheckTrusteePasswordChangedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckTrusteePasswordChangedOperationCompleted);
            }
            this.InvokeAsync("CheckTrusteePasswordChanged", new object[] {
                        username}, this.CheckTrusteePasswordChangedOperationCompleted, userState);
        }
        
        private void OnCheckTrusteePasswordChangedOperationCompleted(object arg) {
            if ((this.CheckTrusteePasswordChangedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckTrusteePasswordChangedCompleted(this, new CheckTrusteePasswordChangedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:CheckValidTrusteeNo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="CheckValidTrusteeNo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CheckValidTrusteeNo(string username) {
            object[] results = this.Invoke("CheckValidTrusteeNo", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckValidTrusteeNoAsync(string username) {
            this.CheckValidTrusteeNoAsync(username, null);
        }
        
        /// <remarks/>
        public void CheckValidTrusteeNoAsync(string username, object userState) {
            if ((this.CheckValidTrusteeNoOperationCompleted == null)) {
                this.CheckValidTrusteeNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckValidTrusteeNoOperationCompleted);
            }
            this.InvokeAsync("CheckValidTrusteeNo", new object[] {
                        username}, this.CheckValidTrusteeNoOperationCompleted, userState);
        }
        
        private void OnCheckValidTrusteeNoOperationCompleted(object arg) {
            if ((this.CheckValidTrusteeNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckValidTrusteeNoCompleted(this, new CheckValidTrusteeNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:GenerateP9", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="GenerateP9_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GenerateP9(string username, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime period, string path, string fileName) {
            object[] results = this.Invoke("GenerateP9", new object[] {
                        username,
                        period,
                        path,
                        fileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateP9Async(string username, System.DateTime period, string path, string fileName) {
            this.GenerateP9Async(username, period, path, fileName, null);
        }
        
        /// <remarks/>
        public void GenerateP9Async(string username, System.DateTime period, string path, string fileName, object userState) {
            if ((this.GenerateP9OperationCompleted == null)) {
                this.GenerateP9OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateP9OperationCompleted);
            }
            this.InvokeAsync("GenerateP9", new object[] {
                        username,
                        period,
                        path,
                        fileName}, this.GenerateP9OperationCompleted, userState);
        }
        
        private void OnGenerateP9OperationCompleted(object arg) {
            if ((this.GenerateP9Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateP9Completed(this, new GenerateP9CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:GetActiveMemberCount", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="GetActiveMemberCount_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public int GetActiveMemberCount() {
            object[] results = this.Invoke("GetActiveMemberCount", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveMemberCountAsync() {
            this.GetActiveMemberCountAsync(null);
        }
        
        /// <remarks/>
        public void GetActiveMemberCountAsync(object userState) {
            if ((this.GetActiveMemberCountOperationCompleted == null)) {
                this.GetActiveMemberCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveMemberCountOperationCompleted);
            }
            this.InvokeAsync("GetActiveMemberCount", new object[0], this.GetActiveMemberCountOperationCompleted, userState);
        }
        
        private void OnGetActiveMemberCountOperationCompleted(object arg) {
            if ((this.GetActiveMemberCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveMemberCountCompleted(this, new GetActiveMemberCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:GetAllMembers", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="GetAllMembers_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetAllMembers() {
            object[] results = this.Invoke("GetAllMembers", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllMembersAsync() {
            this.GetAllMembersAsync(null);
        }
        
        /// <remarks/>
        public void GetAllMembersAsync(object userState) {
            if ((this.GetAllMembersOperationCompleted == null)) {
                this.GetAllMembersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllMembersOperationCompleted);
            }
            this.InvokeAsync("GetAllMembers", new object[0], this.GetAllMembersOperationCompleted, userState);
        }
        
        private void OnGetAllMembersOperationCompleted(object arg) {
            if ((this.GetAllMembersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllMembersCompleted(this, new GetAllMembersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:GetAssignedBoards", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="GetAssignedBoards_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetAssignedBoards(string username) {
            object[] results = this.Invoke("GetAssignedBoards", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssignedBoardsAsync(string username) {
            this.GetAssignedBoardsAsync(username, null);
        }
        
        /// <remarks/>
        public void GetAssignedBoardsAsync(string username, object userState) {
            if ((this.GetAssignedBoardsOperationCompleted == null)) {
                this.GetAssignedBoardsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssignedBoardsOperationCompleted);
            }
            this.InvokeAsync("GetAssignedBoards", new object[] {
                        username}, this.GetAssignedBoardsOperationCompleted, userState);
        }
        
        private void OnGetAssignedBoardsOperationCompleted(object arg) {
            if ((this.GetAssignedBoardsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssignedBoardsCompleted(this, new GetAssignedBoardsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:GetBoardMeetingsAttended1", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="GetBoardMeetingsAttended1_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetBoardMeetingsAttended1(string username) {
            object[] results = this.Invoke("GetBoardMeetingsAttended1", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBoardMeetingsAttended1Async(string username) {
            this.GetBoardMeetingsAttended1Async(username, null);
        }
        
        /// <remarks/>
        public void GetBoardMeetingsAttended1Async(string username, object userState) {
            if ((this.GetBoardMeetingsAttended1OperationCompleted == null)) {
                this.GetBoardMeetingsAttended1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBoardMeetingsAttended1OperationCompleted);
            }
            this.InvokeAsync("GetBoardMeetingsAttended1", new object[] {
                        username}, this.GetBoardMeetingsAttended1OperationCompleted, userState);
        }
        
        private void OnGetBoardMeetingsAttended1OperationCompleted(object arg) {
            if ((this.GetBoardMeetingsAttended1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBoardMeetingsAttended1Completed(this, new GetBoardMeetingsAttended1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:GetBoardMeetingsAttended", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="GetBoardMeetingsAttended_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetBoardMeetingsAttended(string username) {
            object[] results = this.Invoke("GetBoardMeetingsAttended", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBoardMeetingsAttendedAsync(string username) {
            this.GetBoardMeetingsAttendedAsync(username, null);
        }
        
        /// <remarks/>
        public void GetBoardMeetingsAttendedAsync(string username, object userState) {
            if ((this.GetBoardMeetingsAttendedOperationCompleted == null)) {
                this.GetBoardMeetingsAttendedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBoardMeetingsAttendedOperationCompleted);
            }
            this.InvokeAsync("GetBoardMeetingsAttended", new object[] {
                        username}, this.GetBoardMeetingsAttendedOperationCompleted, userState);
        }
        
        private void OnGetBoardMeetingsAttendedOperationCompleted(object arg) {
            if ((this.GetBoardMeetingsAttendedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBoardMeetingsAttendedCompleted(this, new GetBoardMeetingsAttendedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:GetMemberCountsByStatus", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="GetMemberCountsByStatus_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetMemberCountsByStatus() {
            object[] results = this.Invoke("GetMemberCountsByStatus", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberCountsByStatusAsync() {
            this.GetMemberCountsByStatusAsync(null);
        }
        
        /// <remarks/>
        public void GetMemberCountsByStatusAsync(object userState) {
            if ((this.GetMemberCountsByStatusOperationCompleted == null)) {
                this.GetMemberCountsByStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberCountsByStatusOperationCompleted);
            }
            this.InvokeAsync("GetMemberCountsByStatus", new object[0], this.GetMemberCountsByStatusOperationCompleted, userState);
        }
        
        private void OnGetMemberCountsByStatusOperationCompleted(object arg) {
            if ((this.GetMemberCountsByStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberCountsByStatusCompleted(this, new GetMemberCountsByStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:GetPensionerCountsByStatus", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="GetPensionerCountsByStatus_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetPensionerCountsByStatus() {
            object[] results = this.Invoke("GetPensionerCountsByStatus", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPensionerCountsByStatusAsync() {
            this.GetPensionerCountsByStatusAsync(null);
        }
        
        /// <remarks/>
        public void GetPensionerCountsByStatusAsync(object userState) {
            if ((this.GetPensionerCountsByStatusOperationCompleted == null)) {
                this.GetPensionerCountsByStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPensionerCountsByStatusOperationCompleted);
            }
            this.InvokeAsync("GetPensionerCountsByStatus", new object[0], this.GetPensionerCountsByStatusOperationCompleted, userState);
        }
        
        private void OnGetPensionerCountsByStatusOperationCompleted(object arg) {
            if ((this.GetPensionerCountsByStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPensionerCountsByStatusCompleted(this, new GetPensionerCountsByStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:GetTrusteeDetails", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="GetTrusteeDetails_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetTrusteeDetails(string username) {
            object[] results = this.Invoke("GetTrusteeDetails", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTrusteeDetailsAsync(string username) {
            this.GetTrusteeDetailsAsync(username, null);
        }
        
        /// <remarks/>
        public void GetTrusteeDetailsAsync(string username, object userState) {
            if ((this.GetTrusteeDetailsOperationCompleted == null)) {
                this.GetTrusteeDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTrusteeDetailsOperationCompleted);
            }
            this.InvokeAsync("GetTrusteeDetails", new object[] {
                        username}, this.GetTrusteeDetailsOperationCompleted, userState);
        }
        
        private void OnGetTrusteeDetailsOperationCompleted(object arg) {
            if ((this.GetTrusteeDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTrusteeDetailsCompleted(this, new GetTrusteeDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:GetTrusteeEmail", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="GetTrusteeEmail_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetTrusteeEmail(string username) {
            object[] results = this.Invoke("GetTrusteeEmail", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTrusteeEmailAsync(string username) {
            this.GetTrusteeEmailAsync(username, null);
        }
        
        /// <remarks/>
        public void GetTrusteeEmailAsync(string username, object userState) {
            if ((this.GetTrusteeEmailOperationCompleted == null)) {
                this.GetTrusteeEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTrusteeEmailOperationCompleted);
            }
            this.InvokeAsync("GetTrusteeEmail", new object[] {
                        username}, this.GetTrusteeEmailOperationCompleted, userState);
        }
        
        private void OnGetTrusteeEmailOperationCompleted(object arg) {
            if ((this.GetTrusteeEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTrusteeEmailCompleted(this, new GetTrusteeEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:LoginForUnchangedPassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="LoginForUnchangedPassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string LoginForUnchangedPassword(string username, string password) {
            object[] results = this.Invoke("LoginForUnchangedPassword", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginForUnchangedPasswordAsync(string username, string password) {
            this.LoginForUnchangedPasswordAsync(username, password, null);
        }
        
        /// <remarks/>
        public void LoginForUnchangedPasswordAsync(string username, string password, object userState) {
            if ((this.LoginForUnchangedPasswordOperationCompleted == null)) {
                this.LoginForUnchangedPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginForUnchangedPasswordOperationCompleted);
            }
            this.InvokeAsync("LoginForUnchangedPassword", new object[] {
                        username,
                        password}, this.LoginForUnchangedPasswordOperationCompleted, userState);
        }
        
        private void OnLoginForUnchangedPasswordOperationCompleted(object arg) {
            if ((this.LoginForUnchangedPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginForUnchangedPasswordCompleted(this, new LoginForUnchangedPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:UpdateTrusteeAutoGenPassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="UpdateTrusteeAutoGenPassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string UpdateTrusteeAutoGenPassword(string username, string genpass) {
            object[] results = this.Invoke("UpdateTrusteeAutoGenPassword", new object[] {
                        username,
                        genpass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTrusteeAutoGenPasswordAsync(string username, string genpass) {
            this.UpdateTrusteeAutoGenPasswordAsync(username, genpass, null);
        }
        
        /// <remarks/>
        public void UpdateTrusteeAutoGenPasswordAsync(string username, string genpass, object userState) {
            if ((this.UpdateTrusteeAutoGenPasswordOperationCompleted == null)) {
                this.UpdateTrusteeAutoGenPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTrusteeAutoGenPasswordOperationCompleted);
            }
            this.InvokeAsync("UpdateTrusteeAutoGenPassword", new object[] {
                        username,
                        genpass}, this.UpdateTrusteeAutoGenPasswordOperationCompleted, userState);
        }
        
        private void OnUpdateTrusteeAutoGenPasswordOperationCompleted(object arg) {
            if ((this.UpdateTrusteeAutoGenPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTrusteeAutoGenPasswordCompleted(this, new UpdateTrusteeAutoGenPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Trustee:UpdateTrusteePassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", ResponseElementName="UpdateTrusteePassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Trustee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string UpdateTrusteePassword(string username, string password) {
            object[] results = this.Invoke("UpdateTrusteePassword", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTrusteePasswordAsync(string username, string password) {
            this.UpdateTrusteePasswordAsync(username, password, null);
        }
        
        /// <remarks/>
        public void UpdateTrusteePasswordAsync(string username, string password, object userState) {
            if ((this.UpdateTrusteePasswordOperationCompleted == null)) {
                this.UpdateTrusteePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTrusteePasswordOperationCompleted);
            }
            this.InvokeAsync("UpdateTrusteePassword", new object[] {
                        username,
                        password}, this.UpdateTrusteePasswordOperationCompleted, userState);
        }
        
        private void OnUpdateTrusteePasswordOperationCompleted(object arg) {
            if ((this.UpdateTrusteePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTrusteePasswordCompleted(this, new UpdateTrusteePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CheckTrusteeLoginCompletedEventHandler(object sender, CheckTrusteeLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckTrusteeLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckTrusteeLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CheckTrusteePasswordChangedCompletedEventHandler(object sender, CheckTrusteePasswordChangedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckTrusteePasswordChangedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckTrusteePasswordChangedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CheckValidTrusteeNoCompletedEventHandler(object sender, CheckValidTrusteeNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckValidTrusteeNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckValidTrusteeNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GenerateP9CompletedEventHandler(object sender, GenerateP9CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateP9CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateP9CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetActiveMemberCountCompletedEventHandler(object sender, GetActiveMemberCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveMemberCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveMemberCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetAllMembersCompletedEventHandler(object sender, GetAllMembersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllMembersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllMembersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetAssignedBoardsCompletedEventHandler(object sender, GetAssignedBoardsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssignedBoardsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssignedBoardsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetBoardMeetingsAttended1CompletedEventHandler(object sender, GetBoardMeetingsAttended1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBoardMeetingsAttended1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBoardMeetingsAttended1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetBoardMeetingsAttendedCompletedEventHandler(object sender, GetBoardMeetingsAttendedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBoardMeetingsAttendedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBoardMeetingsAttendedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetMemberCountsByStatusCompletedEventHandler(object sender, GetMemberCountsByStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberCountsByStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberCountsByStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetPensionerCountsByStatusCompletedEventHandler(object sender, GetPensionerCountsByStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPensionerCountsByStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPensionerCountsByStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetTrusteeDetailsCompletedEventHandler(object sender, GetTrusteeDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTrusteeDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTrusteeDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetTrusteeEmailCompletedEventHandler(object sender, GetTrusteeEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTrusteeEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTrusteeEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void LoginForUnchangedPasswordCompletedEventHandler(object sender, LoginForUnchangedPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginForUnchangedPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginForUnchangedPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UpdateTrusteeAutoGenPasswordCompletedEventHandler(object sender, UpdateTrusteeAutoGenPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTrusteeAutoGenPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTrusteeAutoGenPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UpdateTrusteePasswordCompletedEventHandler(object sender, UpdateTrusteePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTrusteePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTrusteePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591